# Production Inventory - 6-node pilot (1 Proxmox/Bootstrap + 1 control + 5 compute)
# VLAN 110: 172.31.10.0/24 management; VLAN 111: 172.31.11.0/24 storage/tenant
# Node 1 = bootstrap (Proxmox, MAAS, GitLab, monitoring); control = VM or controller-01; nodes 2-6 = compute+Ceph

all:
  children:
    bootstrap:
      hosts:
        node-01:
          ansible_host: 172.31.10.1
          ansible_user: devops
      vars:
        ansible_python_interpreter: /usr/bin/python3

    control:
      hosts:
        controller-01:
          ansible_host: 172.31.10.2
          ansible_user: devops
      vars:
        ansible_python_interpreter: /usr/bin/python3

    compute:
      hosts:
        compute-01:
          ansible_host: 172.31.10.3
          ansible_user: devops
        compute-02:
          ansible_host: 172.31.10.4
          ansible_user: devops
        compute-03:
          ansible_host: 172.31.10.5
          ansible_user: devops
        compute-04:
          ansible_host: 172.31.10.6
          ansible_user: devops
        compute-05:
          ansible_host: 172.31.10.7
          ansible_user: devops
      vars:
        ansible_python_interpreter: /usr/bin/python3

    ceph-mon:
      hosts:
        controller-01:
      vars:
        ceph_monitor_interface: br0-v110

    ceph-osd:
      hosts:
        compute-01:
        compute-02:
        compute-03:
        compute-04:
        compute-05:
      vars:
        ceph_osd_interface: br0-v111

    network:
      hosts:
        controller-01:
      vars:
        neutron_external_interface: br0-v111

    storage:
      hosts:
        controller-01:
      vars: {}

    monitoring:
      hosts:
        node-01:
      vars:
        monitoring_enabled: true

  vars:
    ansible_user: devops
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
    ansible_python_interpreter: /usr/bin/python3
